feat: use venv for all tutor releases instead of binary
Using binary versions was limiting as:
1. Only Linux_x86_64 and Darwin_x68_64 were supported.
2. The single file binary used whatever python env was loaded at
   the time to install plugins, leading to surprising behavior.

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -5,7 +5,7 @@ set -euo pipefail
 current_script_path=${BASH_SOURCE[0]}
 plugin_dir=$(dirname "$(dirname "$current_script_path")")
 
-# shellcheck source=./lib/utils.bash
+# shellcheck source=../lib/utils.bash
 source "${plugin_dir}/lib/utils.bash"
 
 mkdir -p "$ASDF_DOWNLOAD_PATH"
@@ -13,9 +13,12 @@ mkdir -p "$ASDF_DOWNLOAD_PATH"
 if [ "$ASDF_INSTALL_VERSION" == "nightly" ]; then
 	git clone $GH_REPO -b nightly "$ASDF_DOWNLOAD_PATH"
 else
-	release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME"
-
-	# Download binary to the download directory
-	download_release "$ASDF_INSTALL_VERSION" "$release_file"
-	chmod +x "$release_file"
+	(
+		git clone "$GH_REPO" "$ASDF_DOWNLOAD_PATH"
+		cd "$ASDF_DOWNLOAD_PATH"
+		git checkout --detach "v$ASDF_INSTALL_VERSION"
+	) || (
+		rm -rf "${ASDF_DOWNLOAD_PATH:?}/*"
+		fail "Failed to download tutor correctly."
+	)
 fi
